# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Espresso(object):
    def setupUi(self, Espresso):
        Espresso.setObjectName("Espresso")
        Espresso.resize(800, 470)
        self.table = QtWidgets.QTableWidget(parent=Espresso)
        self.table.setGeometry(QtCore.QRect(0, 0, 800, 470))
        self.table.setObjectName("table")
        self.table.setColumnCount(8)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        self.btnEdit = QtWidgets.QPushButton(parent=Espresso)
        self.btnEdit.setGeometry(QtCore.QRect(694, 422, 101, 31))
        self.btnEdit.setObjectName("btnEdit")

        self.retranslateUi(Espresso)
        QtCore.QMetaObject.connectSlotsByName(Espresso)

    def retranslateUi(self, Espresso):
        _translate = QtCore.QCoreApplication.translate
        Espresso.setWindowTitle(_translate("Espresso", "Form"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Espresso", "ID"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Espresso", "Title"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Espresso", "Sort"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Espresso", "Roasting"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Espresso", "Type"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Espresso", "Taste"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("Espresso", "Price"))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("Espresso", "Volume"))
        self.btnEdit.setText(_translate("Espresso", "Редактировать"))
